/* @generated by engine/generate_pages.py */
import { cache } from 'react';
import Script from "next/script";
import type { Metadata } from "next";
import SnapshotClient from "@/lib/SnapshotClient";
import { loadSnapshot } from "@/lib/loadSnapshot";
import { snapshotMetadata } from "@/lib/snapshotMetadata";

const SLUG = "triolla-io-blog-the-essential-guide-to-designing-a-top-performing-cyber-app-6-1";
const LOCALE = "en";

const _load = cache(() => loadSnapshot(SLUG, LOCALE));

export const generateMetadata = async (): Promise<Metadata> => {
  const { entry } = await _load();
  return snapshotMetadata(entry.slug, entry.locale);
};

export default async function BlogTheEssentialGuideToDesigningATopPerformingCyberApp6Page() {
  const { entry, bodyHtml, widgetProps } = await _load();

  const jsonLdBlocks = [
    ...(entry.head?.jsonLd ?? []),
    ...(entry.head?.jsonLdSynthesized ?? []),
  ];

  return (
    <>
      {jsonLdBlocks.map((block, i) => (
        <Script
          key={i}
          id={`json-ld-${i}-${SLUG}`}
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: block }}
        />
      ))}
      {entry.fontPreloads?.map((href) => (
        <link key={href} rel="preload" href={href} as="font" crossOrigin="anonymous" />
      ))}
      {entry.imagePreloads?.map((preload) => (
        <link
          key={preload.href}
          rel="preload"
          href={preload.href}
          as="image"
          type={preload.type}
          imageSrcSet={preload.imagesrcset}
          fetchPriority="high"
        />
      ))}
      {/* SSR JS preloads — browser starts fetching scripts during HTML parse, not after hydration */}
      {entry.js
        .filter((src) => !/googletagmanager|facebook\.net|hotjar|clarity\.ms|hubspot|hs-scripts|\/\d{7,}\.js/i.test(src))
        .slice(0, 5)
        .map((href) => (
          <link key={href} rel="preload" as="script" href={href} />
        ))}
      {/* SSR snapshot CSS so downloads start during HTML parse — big LCP win. */}
      {entry.css.map((href) => (
        <link key={href} rel="stylesheet" href={href} />
      ))}
      <SnapshotClient entry={entry} bodyHtml={bodyHtml} widgetProps={widgetProps} />
    </>
  );
}

export const dynamic = "force-static";
