import { MetadataRoute } from "next";

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://triolla.io";

const staticRoutes = [
  "/",
  "/about-us",
  "/accessibility-statement",
  "/agritech",
  "/b2b",
  "/b2c",
  "/blog",
  "/branding-studio",
  "/careers",
  "/contact-us",
  "/cyber-security",
  "/dashboard-design",
  "/dev",
  "/device-iot",
  "/fintech-finance",
  "/gaming",
  "/medical-healthcare",
  "/mobile-apps",
  "/portfolio-page",
  "/privacy-policy",
  "/saas-platforms",
  "/service-detail",
  "/services",
  "/services-back-end-dev",
  "/services-character-design",
  "/services-creative-concept",
  "/services-design-system-creation",
  "/services-front-end-dev",
  "/services-logo-design",
  "/services-motion-design",
  "/services-motion-design-old",
  "/services-presentations",
  "/services-product-stars",
  "/services-product-ux-ui-design",
  "/services-prototyping",
  "/services-ui-design",
  "/services-user-testing",
  "/services-ux-research",
  "/services-wireframing",
  "/startups-tech",
  "/technology",
  "/terms-of-use",
];

const blogRoutes = [
  "/blog-10-principles-for-using-color-in-ux-ui-design",
  "/blog-10-ux-ui-design-rules-you-should-never-break",
  "/blog-5-examples-of-web-animation-done-right",
  "/blog-7-emerging-ui-ux-design-trends-every-development-team-should-be-aware-of",
  "/blog-a-complex-project-becomes-simple-with-the-ux-canvas",
  "/blog-a-comprehensive-guide-to-mastering-mobile-app-design-for-israeli-startups-and-companies",
  "/blog-a-comprehensive-guide-to-mastering-mobile-app-design-for-israeli-startups-corporates",
  "/blog-ahead-of-the-curve-key-ux-ui-developments-to-watch-in-2024",
  "/blog-amazon-unveils-a-fresh-modern-design-for-the-prime-video-app",
  "/blog-animation-in-ui-design-from-concept-to-reality",
  "/blog-behind-the-wheel-ux-design-aspects-for-smart-cars",
  "/blog-behind-the-wheel",
  "/blog-best-practices-for-cards",
  "/blog-best-practices-for-minimalist-design",
  "/blog-beyond-graphics-deep-user-experience-design-for-tomorrows-gaming-apps",
  "/blog-calcalist-triolla-named-best-ux-ui-agency-in-israel",
  "/blog-can-design-be-too-user-friendly-exploring-the-limits-of-ux-ui-in-product-design",
  "/blog-classical-conditioning-and-user-experience",
  "/blog-clutch-recognizes-triolla-among-the-top-ux-design-companies-for-2021",
  "/blog-custom-ux-ui-design-for-power-bi-tableau-qlik-sap-oracle-bi",
  "/blog-cybersecurity-design-ux-a-founder-playbook",
  "/blog-designing-an-engaging-and-effective-agritech-app",
  "/blog-designing-intuitive-and-secure-iot-products-for-the-future",
  "/blog-enhancing-customer-satisfaction-through-positive-user-experience-and-user-delight",
  "/blog-everything-you-need-to-know-about-wireframes",
  "/blog-f35-ux-vertigo",
  "/blog-ftue-first-time-user-experience",
  "/blog-globs-best-agency-in-israel",
  "/blog-go-mobile-conference-7-ui-animation",
  "/blog-how-a-design-system-can-transform-your-digital-product-essential-insights-for-ux-ui-designers",
  "/blog-how-the-industrys-leading-ux-ui-agency-can-also-be-a-boutique-ux-studio",
  "/blog-how-to-create-web-animation-the-right-way",
  "/blog-how-to-prepare-for-a-product-manager-interview",
  "/blog-how-to-stay-ahead-key-ux-ui-trends-and-the-future-of-user-experience-in-2024",
  "/blog-how-to-sync-with-your-product-designer-pros-best-practices",
  "/blog-how-to-use-animation-to-improve-ux-2",
  "/blog-how-to-use-animation-to-improve-ux",
  "/blog-how-user-experience-design-drives-startup-success-tips-for-building-winning-digital-products",
  "/blog-how-will-ux-ui-shape-our-technological-future",
  "/blog-if-ux-is-life-itself-it-must-be-designed-for-people-everywhere-and-always",
  "/blog-in-house-designers-or-a-ux-ui-agency-everything-you-need-to-know",
  "/blog-iso-27001-2025-2026",
  "/blog-lets-talk-microcopy-how-small-words-create-a-big-user-experience-in-ux-ui-design",
  "/blog-level-up-your-gaming-app-with-triollas-expert-ux-tips-boost-user-engagement-and-retention",
  "/blog-maximize-the-potential-of-iot-with-user-experience-design-by-triolla-ux",
  "/blog-mobile-design-best-practices",
  "/blog-navigating-the-future-of-ux-design-2",
  "/blog-navigating-the-future-of-ux-design",
  "/blog-nine-examples-of-mobile-ux-innovation-in-2019",
  "/blog-nlp-ux",
  "/blog-onboarding-process-in-saas-products-how-the-big-companies-do-it",
  "/blog-pms-own-your-product-design-process-with-these-simple-steps",
  "/blog-power-up-your-design-system-with-figma-and-triolla",
  "/blog-power-users-the-key-to-your-apps-success-how-to-make-it-happen",
  "/blog-pro-tip-how-to-improve-landing-page-design",
  "/blog-product-managers-manage-your-product-design-process-with-these-simple-steps",
  "/blog-product-managers-must-understand-why-is-tiktok-so-addictive",
  "/blog-product-user-fit-comes-before-product-market-fit",
  "/blog-prompt-engineering-for-ux-ui-design-how-to-use-prompts-to-elevate-your-design-process",
  "/blog-prototyping-tools-for-ux-designers",
  "/blog-revolutionizing-healthcare-with-ux-design-2",
  "/blog-revolutionizing-healthcare-with-ux-design",
  "/blog-saas-product-tour-trends-how-great-companies-onboard-users-in-2018",
  "/blog-six-things-you-need-to-check-before-hiring-a-ux-ui-agency",
  "/blog-tadirans-smart-home-app-design-that-makes-innovation-accessible",
  "/blog-the-3-most-common-pain-points-when-hiring-ui-ux-agency-for-a-saas-product",
  "/blog-the-easy-and-effective-way-to-collect-feedback-from-your-product-users",
  "/blog-the-essential-guide-to-designing-a-top-performing-cyber-app-6",
  "/blog-the-essential-guide-to-designing-a-top-performing-cyber-app-mastering-cyber-ux",
  "/blog-the-essential-questions-to-consider-before-meeting-with-a-ux-ui-design-agency",
  "/blog-the-fintech-ux-playbook",
  "/blog-the-guide-product-roadmap",
  "/blog-the-hottest-ui-design-tips-for-dashboards",
  "/blog-the-questions-every-entrepreneur-and-product-manager-must-be-able-to-answer-in-a-kickoff-meeting",
  "/blog-the-real-difference-between-a-product-manager-pm-and-a-product-owner-po",
  "/blog-the-ultimate-product-design-process-the-best-practice-used-by-google-facebook-netflix-etc",
  "/blog-the-ultimate-product-design-process-the-proven-method-used-by-google-facebook-netflix-and-more",
  "/blog-the-unicorns-secret-to-conquering-product-success",
  "/blog-triolla-an-industry-leader-is-actually-a-boutique-ux-studio",
  "/blog-triollas-mobile-app-ux-mastery-will-make-your-app-a-sensation",
  "/blog-ui-company-boosting-your-products-chances-of-success",
  "/blog-unleash-the-power-of-your-mvp-to-accelerate-your-growth-ux-design-for-startups",
  "/blog-user-experience-design-for-apps-thats-nothing-short-of-excellent",
  "/blog-user-experience-design-in-agritech-products-for-the-agriculture-industry",
  "/blog-user-experience-ux-design-is-the-design-of-life-itself",
  "/blog-user-journey-how-to-do-it-right",
  "/blog-ux-design-trends-for-2018",
  "/blog-ux-designer-or-ux-design",
  "/blog-ux-fintech-expert-what-does-it-mean",
  "/blog-ux-in-medtech-when-trust-is-a-matter-of-life-and-death",
  "/blog-ux-is-life-design-it-for-humans",
  "/blog-ux-ui-design-the-real-way-to-motivate-your-users",
  "/blog-uxui-faqs",
  "/blog-what-does-it-mean-to-be-a-ux-expert-in-fintech",
  "/blog-what-is-ooux-understanding-object-oriented-ux-in-product-and-interface-design",
  "/blog-why-every-company-today-needs-a-custom-dashboard-for-business-management-and-control",
  "/blog-why-every-modern-company-needs-a-stellar-dashboard-ui-insights-from-triolla",
  "/blog-why-is-a-ux-survey-a-crucial-step-in-product-definition",
  "/blog-why-is-ux-ui-created-as-a-team-effort",
  "/blog-why-ux-ui-design-matters-in-fintech",
  "/blog-wisdom-hub-invite",
];

const languageVersions = ["en", "he"];

export default function sitemap(): MetadataRoute.Sitemap {
  const sitemap: MetadataRoute.Sitemap = [];

  // English pages
  [...staticRoutes, ...blogRoutes].forEach((route) => {
    sitemap.push({
      url: `${BASE_URL}${route}`,
      lastModified: new Date(),
      changeFrequency: route.startsWith("/blog") ? "never" : "weekly",
      priority: route === "/" ? 1.0 : route.startsWith("/blog") ? 0.7 : 0.8,
      alternates: {
        languages: {
          he: `${BASE_URL}/he${route}`,
          en: `${BASE_URL}${route}`,
        },
      },
    });
  });

  // Hebrew pages
  [...staticRoutes, ...blogRoutes].forEach((route) => {
    sitemap.push({
      url: `${BASE_URL}/he${route}`,
      lastModified: new Date(),
      changeFrequency: route.startsWith("/blog") ? "never" : "weekly",
      priority: route === "/" ? 1.0 : route.startsWith("/blog") ? 0.7 : 0.8,
      alternates: {
        languages: {
          he: `${BASE_URL}/he${route}`,
          en: `${BASE_URL}${route}`,
        },
      },
    });
  });

  return sitemap;
}
