/* @generated by engine/generate_pages.py */
import { cache } from 'react';
import Script from "next/script";
import type { Metadata } from "next";
import SnapshotClient from "@/lib/SnapshotClient";
import { loadSnapshot } from "@/lib/loadSnapshot";
import { snapshotMetadata } from "@/lib/snapshotMetadata";

const SLUG = "triolla-io-he-%d7%94%d7%a9%d7%99%d7%a8%d7%95%d7%aa%d7%99%d7%9d-%d7%a9%d7%9c%d7%a0%d7%95-%d7%9e%d7%a6%d7%92%d7%95%d7%aa";
const LOCALE = "he";

const _load = cache(() => loadSnapshot(SLUG, LOCALE));

export const generateMetadata = async (): Promise<Metadata> => {
  const { entry } = await _load();
  return snapshotMetadata(entry.slug, entry.locale);
};

export default async function HeHeD794D7A9D799D7A8D795D7AaD799D79dD7A9D79cD7A0D795D79eD7A6D792D795D7AaPage() {
  const { entry, bodyHtml, widgetProps } = await _load();

  const jsonLdBlocks = [
    ...(entry.head?.jsonLd ?? []),
    ...(entry.head?.jsonLdSynthesized ?? []),
  ];

  return (
    <>
      {jsonLdBlocks.map((block, i) => (
        <Script
          key={i}
          id={`json-ld-${i}-${SLUG}`}
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: block }}
        />
      ))}
      {entry.fontPreloads?.map((href) => (
        <link key={href} rel="preload" href={href} as="font" crossOrigin="anonymous" />
      ))}
      {entry.imagePreloads?.map((preload) => (
        <link
          key={preload.href}
          rel="preload"
          href={preload.href}
          as="image"
          type={preload.type}
          imageSrcSet={preload.imagesrcset}
          fetchPriority="high"
        />
      ))}
      {/* SSR snapshot CSS so downloads start during HTML parse — big LCP win. */}
      {entry.css.map((href) => (
        <link key={href} rel="stylesheet" href={href} />
      ))}
      <SnapshotClient entry={entry} bodyHtml={bodyHtml} widgetProps={widgetProps} />
    </>
  );
}

export const dynamic = "force-static";
