export default function Page() {
  return (
    <div className="max-w-[900px] mx-auto px-5 sm:px-10 py-[120px]">
      <h1 className="font-bold text-[48px] md:text-[64px] leading-[1.1] text-black mb-12">Terms Of Use</h1>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Welcome to www.triolla.io (the “Website”). The Website is owned and operated by Triolla Ltd. and its corporate group affiliates and subsidiaries (collectively, “Triolla”, “we” and “our“).</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Please carefully read the following terms and conditions (the “Terms” or “Terms of Use“). The Terms constitute a binding agreement between you and Triolla. By accessing the Website or by using it in any other manner, you indicate your acceptance of these Terms. If you do not agree to these Terms of Use, you may not access the Website or use it in any manner.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">About the Website</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">The Website provides content and information about Triolla technology, products, and services. It also provides information regarding Triolla itself as well as open positions at Triolla.
The Website’s content is presented for informative purposes only.
The Website was originally developed by Y&A Software Development Ltd.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">When you contact us</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">You have various ways of contacting us through the Website. However, nothing on the Website or in your submitted inquiries requires us to make any engagements or business arrangements with you, partner with you, provide any products or services, engage in any present or future marketing activities, or engage in any discussions or negotiations with you.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">If you apply for an open position at Triolla, be advised that we are not obligated to consider your candidacy, contact you regarding your application or hire you.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Acceptable use of the Website</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">When using the Website, you must refrain from :</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Breaching these Terms or any other applicable Website rules and instructions that we may provide;
Interfering with, burdening or disrupting the functionality of the Website;
Breaching the security of the Website or identifying any security vulnerabilities in it;
Circumventing or manipulating the operation, or functionality of the Website, or attempting to enable features or functionalities that are otherwise disabled, inaccessible or undocumented in the Website;
Using or launching any automated system, including without limitation robots, crawlers and similar applications to collect and compile content from the Website;
Displaying the Website or any part thereof in an exposed or concealed frame, or linking to elements or portions of the Website, independently from the web pages on which they originally appear;
Displaying content from the Website, including by any software, feature, gadget or communication protocol, which may alter the content or its design;
Impersonating any person or entity, or making any false statement pertaining to your identity, employment, agency or affiliation with any person or entity;
Collecting, harvesting, obtaining or processing personal information of or about other users of our Website; and
Linking to the Website from web pages that contain pornographic content or content that is unlawful or encourages prohibited activity such as racism or wrongful discrimination.
Engaging in any activity that constitutes a criminal offense or gives rise to civil liability;
Violating any applicable law.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Information you submit</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Unless specifically requested, Triolla does not solicit nor does it wish to receive any confidential, secret or proprietary information or other material from you through the Website, any of its services, by e-mail, or in any other way.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">By submitting or sending information or other material to Triolla you represent and warrant that the information is original to you and that no other party has any rights to the material.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">By submitting or sending information or other material to Triolla you grant Triolla the royalty-free, unrestricted, worldwide, perpetual, irrevocable, non-exclusive and fully sub-licensable right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such material (in whole or part) worldwide and/or to incorporate it in other works in any form, media, or technology now known or later developed. You also warrant that any “moral rights” in posted materials have been waived.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">You agree and acknowledge that by using this Website, any and all communications and information transmitted by you to or through the Website will not be treated as confidential or proprietary.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">You agree to defend, indemnify and hold Triolla and its directors, officers, employees, agents and affiliates harmless from any and all claims, liabilities, costs and expenses, including reasonable attorneys’ fees, arising in any way from your use of the Website or the placement or transmission of any message, content, information, software or other materials through the Website by you.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Links</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">The Website may contain links to content published on other websites provided by third parties. We do not operate or monitor these websites and content. You may find them or the information and content posted there not compatible with your requirements or objectionable.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">By linking to a certain website, we do not endorse, or sponsor its content, or confirm its accuracy, credibility, authenticity, reliability, validity, integrity, or legality. We assume no responsibility or liability for such third party websites or content, or their availability, or for any transactions or dealings made between you and such third party websites.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Privacy</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">We respect your privacy. The Website’s current privacy policy is available here. It forms an integral part of these Terms.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Intellectual Property</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">The intellectual property rights associated with the Website, including copyrights, trademarks, trade names, patents, trade secrets, work methods and processes, and any other right, are the sole property of Triolla, or its third party licensors. These rights apply, among others, to information, articles, images, content, graphic design, data and its processing, domain name, the Website’s “look and feel”, computer code and any other detail concerning its operation.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Do not copy, duplicate, distribute, sell, make available, market and translate any information, including trademarks, images, pictures, texts and computer code from the Website, without Triolla’s explicit prior and written consent.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Triolla’s marks, logos, icons, images and symbols on the Website (whether registered or not) as well as the Website’s domain name – are the sole property of Triolla. You may not use them without our prior written consent. Nothing contained in the Website should be construed as granting, by implication or otherwise, any license or right to use any of these Trademarks without express written permission of Triolla.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Other names, company names, brand names, registered and unregistered trademarks or service marks and logos are the property of Triolla or their respective holders. Nothing contained in the site should be construed as granting, by implication or otherwise, any license or right to use any of such marks without express written permission of the owner or rights holder with respect to such use.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Changes and Availability</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">From time to time, we may change the Website’s structure, layout, design or display, as well as the scope and availability of the information and content therein, without prior notice. Changes of this type by their very nature may result in glitches or cause inconvenience of some kind.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">The operation of the Website depends on various factors such as software, hardware and communication networks of Triolla, its contractors and suppliers. By their nature, these factors are not fault free.</p>
        <p className="text-[16px] md:text-[18px] leading-[1.7] text-black/70 mb-5">Changes to the Terms</p>
    </div>
  );
}
