/* @generated by engine/extract_shared_components.py */
// Shared snapshot header extracted from the longest common HTML
// prefix/suffix of this locale's fragments. Do not edit by hand — this file
// is regenerated by the pipeline's shared_components stage.

const HTML = "\n<div  class=\"main_container\">\n<style type=\"text/css\"></style>\n\t    \t<div  class=\"headerticker\">\n    \t<a class=\"tickclose\" role=\"button\" tabindex=\"0\" aria-label=\"Close\"><img width=\"13\" height=\"13\" alt=\"\" src=\"/assets/_cas/4726ac0e14c6d0b3e9ca996819e656eeb9209e7d2bead02c8b42cd7657c03e4d.svg\"></a>\n    \t<ul><li>Pitangoux is now Triolla \u2013<Br> We\u2019ve rebranded! Hello and welcome!</li></ul>\n    </div>\n            <div  class=\"header headnewact\">\n    \t<div  class=\"header_wrap\">\n        \t<div class=\"header_in cf\">\n            \t\n            \t                <div class=\"logo\">\n                \t<a href=\"/\">";

export default function ShellHeader() {
  return <div data-snapshot-shell="header" dangerouslySetInnerHTML={{ __html: HTML }} />;
}
